### ISSUE TITLE
グラフのサイズをyamlで設定できるようにする

### ISSUE THREAD

**Issue by rkoyama1623-jsk** [kindsenior/log_plotter#50]
#43 の議論で出た仕様の実装
layout.yamlに
```yaml
- title: watt
  legends:
    - { key: watt, id: [0-5] }
  height: 400
  width: 500
```
のように書くと，グラフのサイズを設定できるようにしたい
