### ISSUE TITLE
別の時刻のログを一つのグラフに描画できるようにしたい

### ISSUE THREAD

**Issue by rkoyama1623-jsk** [kindsenior/log_plotter#51]
別の実験のログを一つのグラフに描画する機能があったら嬉しいです．
比較的大きな変更になりそうなので，とりあえず，layout.yamlの書き方を検討するスレッドになればと思います．
ぱっと思いつくのは，
layout.yamlに新たなオプションをつける方法で，
```yaml
- title: watt
  legends:
    - { key: watt, id: [0-5], path: /path/to/log }
```
legendsに対してログへのパスを直書きするオプションを追加する方法です．
ファイルの構成が変わったとき用に，相対パスをサポートして，
ログファイルの近くにlayout.yamlを置いておくという運用方法が考えられます．
