### ISSUE TITLE
plot.yamlのinclude展開

### ISSUE THREAD

**Issue by kyawawa** [kindsenior/log_plotter#55]
最近手元のyamlファイルが膨大になってきたので，前ちらっと話に上がったこちらを進めてもらえると非常に助かりますが，お時間ありますでしょうか？ > @Tnoriaki

**Comment by Tnoriaki** [comment]
2017年1月2日(月) 18:32 Tatsuya Ishikawa <notifications@github.com>:

**Comment by Tnoriaki** [comment]
分かりました.調べておきます.

**Comment by Tnoriaki** [comment]
@kyawawa 
http://stackoverflow.com/questions/528281/how-can-i-include-an-yaml-file-inside-another
こちらのClass-Based Solutionはどうでしょうか？

**Comment by kyawawa** [comment]
ありがとう
うーむ，なんか，例えば6dofleg_test.yamlに
```yaml
watt:
  func: plot_watt
  data:
    - { log: RobotHardware0_dq, column: [0,1,2,3,4,5]  }
    - { log: RobotHardware0_tau, column: [0,1,2,3,4,5] }
```
と書いていたとして，plot.yamlが
```yaml
!include 6dofleg_test.yaml
```
単体だと動くけど，
```yaml
!include 6dofleg_test.yaml

12V:
  func: plot_12V
  data:
    - { log: RobotHardware0_servoState, column: [0,1,2,3,4,5] }
```
というふうにつなげると，
```
yaml.scanner.ScannerError: mapping values are not allowed here
```
というエラーが出ますね

**Comment by Tnoriaki** [comment]
@kyawawa 
この方法だと階層的にincludeしていくので
現状のyamlのloadの形式を変えるか
他の方法を使うかな気がしますね…

前者だと
一番おおもとのplot.yamlの形式を
```
hoge1: !include hoge1.yaml
hoge2: !include hoge2.yaml
hoge3: !include hoge3.yaml
```
もしくは
```
!include hoge1.yaml
!include hoge2.yaml
!include hoge3.yaml
```
みたいににする事になると思います.

**Comment by rkoyama1623-jsk** [comment]
yaml.loadの中で処理を完結させようと思うと，確かにそのような方法になると思いますが，
やりたいことは，ただファイルを分割すればよいのではなく，プロットルールの継承とオーバーライドなのだと思います．

個人的には，
A.yaml
```
aaa1: ...
aaa2: ...
```
B.yaml
```
bbb1: ...
bbb2: ...
```
X.yaml
```
include: [A.yaml, B.yaml, C.yaml]
xxx: ....
```
のような状況で，X,yamlを読み込むと，
includeを認識して， [A.yaml, B.yaml, C.yaml]を順番にマージするという関数を再帰的に適用して
X.yaml
```
aaa1: ...
aaa2: ....
bbb1: ...
bbb2: ...
...

xxx: ...
````
ができれば良いのではないかと思っています．(keyがかぶったら，後からloadしたファイルでオーバーライドする．)

もうひとつの案としては，plot.yamlとplot_method.pyを統合して，plotの依存関係をpythonファイルで記述することにしてしまうと，pythonの継承やimportをそのまま利用できて拡張性の高いものになりそうです．（もう少し吟味が必要ですが．．．）

**Comment by rkoyama1623-jsk** [comment]
以下は少し話がずれるので，読み飛ばして頂いて構わないです．

当初，yamlのincludeは異なるロボットで共有できる部分を一つのyamlファイルにまとめたいというところから始まったので，今回のニーズに応えられるかがわかっていないです．

plot.yamlの量が増える理由は複数ありそうなので，その原因をもう少し，明確にできたら今後の参考になると思います．現状，私の理解では，

1. 新規のポートを追加すると，ログファイルをそのままプロットするだけで良いのにplot.yamlの追加編集が必要
2. 複数のログを組み合わせたプロットを定義すると，組み合わせの数だけplot_xxを定義する必要がある．

が主な原因で，この問題を解決するには，

1. ログのプロットをするだけなら，plot.yamlの定義を省略できるようにする．
2. 関数の組み合わせができるようにする．（#25 のような汎用的な関数の組み合わせを使えるようにする）

が必要だと思います．2はyamlファイルの中で実現するのは，ハードなので，plot.yaml(とplot_method.py)をpythonスクリプトに置き換える必要があるかもしれないと考えています．

**Comment by Tnoriaki** [comment]
@rkoyama1623 さん

> yaml.loadの中で処理を完結させようと思うと，確かにそのような方法になると思いますが，
> やりたいことは，ただファイルを分割すればよいのではなく，プロットルールの継承とオーバーライドなのだと思います．

についてですが,
@rkoyama1623 さんがやりたいのは
https://pypi.python.org/pypi/metayaml/0.9
みたいなことでしょうか？

**Comment by rkoyama1623-jsk** [comment]
おぉ、私が個人的に思っていたのはこんな感じです。
さすが!

yamlの変更は影響が大きいので@Tnoriaki が見つけてくれたパッケージの仕様をもう少しよく確認したいのと、総意を形成しておきたいですね。

@kyawawa はこの流れで目的を達成できそうでしょうか?

**Comment by rkoyama1623** [comment]
> https://pypi.python.org/pypi/metayaml/0.9

julia風に文字列の中に式を埋め込めるのはすごいかも。
```yaml
hour: ${60*60} # just simple python expression delay: ${hour*2} # delay is two hour or 7200 seconds 
```

**Comment by rkoyama1623-jsk** [comment]
> https://pypi.python.org/pypi/metayaml/0.9

julia風に文字列の中に式を埋め込めるのはすごいかも。
```yaml
hour: ${60*60} # just simple python expression 
delay: ${hour*2} # delay is two hour or 7200 seconds 
```

**Comment by kyawawa** [comment]
はい，私はこれで良さそうです
式埋めこみがどこまで使えそうかはわからないところですね

**Comment by kindsenior** [comment]
metayamlの機能自体については
- 実現したい機能がある
- 既に書いているyamlに対する変更が少ない

の2点に関して問題ないと思います
あとは信頼性ですが，これは使ってみないと何とも言えないのでとりあえずやってみるんでしょうかね

**Comment by Tnoriaki** [comment]
> 既に書いているyamlに対する変更が少ない

こちらに関してですが,
metayamlは辞書型のみでリストは対応してなさそうなので
hoge_layout.yamlの方は書き方を変更しなければいけなさそうですが大丈夫でしょうか？
変更の仕方としては

- 全体をまとめてkeyを一つ与える
- titleをkeyにする

があると思います.

**Comment by rkoyama1623-jsk** [comment]
hoge_layout.yamlは，今のところ，include展開できなくてもよい気もしますが，
後々metayamlの機能があったら便利かもしれないですね．

metayamlをlayout.yamlに導入する場合は

> - 全体をまとめてkeyを一つ与える

が良いです．

> - titleをkeyにする

は，辞書形式だとyamlで書いた順序が保たれないので．

グラフのレイアウト情報をkeyでまとめておくと，記述量は少しだけ増えますが，
その他の情報（フォントなど）を別のkeyで指定できるので，後々の拡張性は向上すると思います．

私は，metayamlを導入するかはどちらでも良いです．

**Comment by rkoyama1623-jsk** [comment]
@Tnoriaki と話して，metayamlでリストを利用すると，metayamlを利用するメリットがあまりないということがわかったので，もう少し検討したい．

**Comment by Tnoriaki** [comment]
@rkoyama1623 と話して
全体をまとめて"main"というkeyを一つ与え
かつ
titleをkeyにするという方式を取るのが良いのではないかということになりました.
#57 
にて変更いたしましたので皆さんご確認よろしくお願い致します.

**Comment by rkoyama1623-jsk** [comment]
yamlの書き方について#57 の後方互換性を整理すると，


1. plot.yamlは後方互換性を維持している(上位互換)

新たに，
```yaml
extend: [xxx_common.yaml, ....]
```
を追加できるようになった．


2. layout.yamlは後方互換でない

変更前
```yaml
- title: watt
  legends:
    - { key: watt, id: [0-5] }
- title: joint_angle
  legends:
    - { key: xxx, id: [0-5] }
```
変更後
```yaml
main:
  watt:
    legends:
      - { key: watt, id: [0-5] }
  joint_angle:
    legends:
      - { key: xxx, id: [0-5] }
```
新たにできるようになったことは,他のファイルのinclude展開と式の埋め込み

```yaml
extend: [xxx_layout.yaml]
main:
  watt:
    legends:
      - { key: watt, id: [$(range(6))] }
```
layout.yamlの記述方法が増えてしまった点が許容可能かどうか検討をよろしくお願いします．
main以下の部分は`collections.OrderedDict`(順序付きdict)として読み込まれます．
metayamlのメリットを利用するためにはこうするしか無さそうです．

**Comment by kindsenior** [comment]
> layout.yamlの記述方法が増えてしまった点が許容可能かどうか検討をよろしくお願いします．

これは記述量について許容可能かという意味でしょうか？それについては問題ないと思います
ただ，議論についていきてないだけかもしれませんが，
>全体をまとめて"main"というkeyを一つ与え
かつ
titleをkeyにするという方式を取るのが良いのではないかということになりました.

の理由が今一理解できていません．
> metayamlのメリットを利用するためにはこうするしか無さそうです．

が，titleをkeyにする理由でしょうか？
layoutの"main"keyの中を辞書形式にした場合，layout.yamlで記入した順にグラフを表示させることはできるのでしょうか？

**Comment by rkoyama1623-jsk** [comment]
> layoutの"main"keyの中を辞書形式にした場合，layout.yamlで記入した順にグラフを表示させることはできるのでしょうか？

はい，できます．理由は以下の「metayamlの事情」の１です．

metayamlの事情３つ

#### 1. 一番上の階層以外の辞書は，collections.OrderedDictで読み込まれる．
collections.OrderedDicはほぼ辞書だけれど，格納された順番を保持しているらしいです．

http://shannon-lab.org/?p=1743

#### 2. 一番上の階層でリストを利用できない．(extendなどが辞書のキーであるため)
以下は読めない
```yaml
- hoge
- fuga
```
以下は読める．
```yaml
sample:
  - hoge
  - fuga
```
#### 3. リストをオーバーライドされた場合は，すべてが入れ替わる．

file1.yaml
```yaml
mylist:
  - hoge
  - fuga
```
file2.yaml
```yaml
extend: [file1.yaml]
mylist:
  - aaa
  - bbb
```
file2.yamlをreadすると, file1のリストはすべてオーバーライドされる
```yaml
mylist:
  - aaa
  - bbb
```

#### 今回の判断基準
1. layout.yamlもinclude展開できると，便利かもしれない．  
abc用のlayout.yamlとst用のlayout.yamlを両方includeするだけで，バランス制御周りのプロットを一気に見れるなど．

metayamlを利用する場合以下の２つの条件が必要になります．

2. 全体をまとめて"main"というkeyを一つ与える  
１と２のため，一番上の階層をリストにできないし，辞書にすると順番が保持できない．
metayamlの事情2のため，まず辞書のキーを置くと，順番を維持した辞書として扱える
3. titleをkeyにするという方式を取る
metayaml3のために，リストにすると，include展開の意味がなくなるため順番付き辞書として読み込ませる．
