### ISSUE TITLE
yrangeのデフォルト値が0~1になっている

### ISSUE THREAD

**Issue by Tnoriaki** [kindsenior/log_plotter#87]
@rkoyama1623 
https://github.com/kindsenior/log_plotter/pull/80/files#diff-b598a12c7bd280a53f1ba86a93eccaa9L433
の変更で
yrangeのデフォルト値が0~1になっている気がしますがこれは想定の挙動でしょうか？

現状
https://github.com/kindsenior/log_plotter/blob/master/src/log_plotter/datalogger_plotter_with_pyqtgraph.py#L210-L220
をコメントアウトすることでデフォルト値がall rangeになります.

**Comment by Tnoriaki** [comment]
あ、もしかしたら僕が分離した時のバグかもしれません…

**Comment by rkoyama1623-jsk** [comment]
なぜ，0~1がデフォルト値になってしまうのか，原因をまだ見つけられていませんが，

> 現状
https://github.com/kindsenior/log_plotter/blob/master/src/log_plotter/datalogger_plotter_with_pyqtgraph.py#L210-L220
をコメントアウトすることでデフォルト値がall rangeになります.

の部分は，直書きしている感が強いので，変更して良いと思います．

**Comment by Tnoriaki** [comment]
#80 のバグ2
i行でゼロ点だしすると
i+1行目からさきが表示がバグる

**Comment by Tnoriaki** [comment]
plot時にrangeを決める　or   linkaxes()でrangeを決める

バグ１
- plotした後でないとレンジがわからない　＋　plotの前でレンジを決めている

バグ2
- 変数のセットタイミングがおかしい
- 今ゼロ点だしはplotするときに右にずらす
- ゼロ点だしはreadData()でやったほうがいい
- そもそもyamlにそれぞれ書けるようにするのはmisleeding

**Comment by rkoyama1623-jsk** [comment]
検討不十分でした．すみませんでした．

**Comment by kindsenior** [comment]
すみません．よく分かっていませんが，
>現状
https://github.com/kindsenior/log_plotter/blob/master/src/log_plotter/datalogger_plotter_with_pyqtgraph.py#L210-L220
をコメントアウトすることでデフォルト値がall rangeになります.

の部分はやっても問題ないということでしょうか？
それならば，全てy値に関してはリンクしないというのでいいんじゃないでしょうか

**Comment by rkoyama1623-jsk** [comment]
> すみません．よく分かっていませんが，
>>    現状
https://github.com/kindsenior/log_plotter/blob/master/src/log_plotter/datalogger_plotter_with_pyqtgraph.py#L210-L220
をコメントアウトすることでデフォルト値がall rangeになります.  

>  の部分はやっても問題ないということでしょうか？

やってもよいのですが，それだけではバグを直しきれないです．

現在の仕様は一旦置いておくとして，ｙ値のリンクを含めて，決めなければ行けない仕様は，
以下の点です．
- [ ] すべてのｙ値はリンクしなくて良いか？→良いという方向
- [ ] xRangeは全グラフでリンクしているのでよいか？その場合，以下のような選択肢がある．
    - xRangeが全グラフでリンクする場合，xRangeはlayout.yamlの全体に対して設定し，yRangeはグラフごとに決められるようにする
    layout.yamlの例
    ```yaml
    xRange: {min: 10, max: 100} # ログのt=10~100秒をプロットする．
    main:
        title1:
            legends: {...}
        yRange: {min; -10, max: 10}
    ```
    - xRangeの設定はグラフ毎に行えるようにし，一つのグラフでもxRangeの設定があったら，xRangeのリンクはしない
    ```yaml
    main:
        title1:
            legends: {...}
        xRange: {min: 10, max: 100} # ログのt=10~100秒をプロットする．
        yRange: {min; -10, max: 10}
    ```
- [ ] ゼロ点出しの機能は必要か？以下の選択肢がありうる．
    - ゼロ点出しは，別途データをトリムするtrim.pyみたいなスクリプトを用意し，トリミングしたデータをプロットすることで実現する
    - ゼロ点出しは，layout.yamlの全体に対しての設定として記述し，readDataのオプションとして，ゼロ点のオフセットを与えられるようにする．
    layout.yamlの例
    ```yaml
    xRange: {min: 10, max: 100, zero: 11} # ログの10~100秒をプロットし，t=11をゼロとする．
    main:
        title1:
            ....
    ```
    - ゼロ点出しは，グラフ毎に設定できるようにし，ゼロ点出しの設定をしたグラフについては，plotDataのオプションとしてオフセットを与えられるようにする．
    layout.yamlの例
    ```yaml
    main:
        title1:
            legends:
                ...
            xRange: {min: 10, max: 100, zero: 11} # ログの10~100秒をプロットし，t=11をゼロとする．
    ```
